version: '3.1'

services:
  backend-dev:
    image: backend_dev:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
    container_name: backend-dev
    ports:
      - 5000:5000
    volumes:
      - ./../:/thesis/backend
    profiles:
      - dev
  backend-test:
    image: backend_test:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
    container_name: backend-test
    ports:
      - 5000:5000
    volumes:
      - ~/thesis_server_config/natsio_config:/etc/natsio_config
      - ~/thesis_logs/natsio:/var/log
      - ~/thesis_server_config/certs:/etc/certs
      - ~/thesis_server_config/cred:/etc/cred
    environment:
      - ContainerName=backend-prod
      - RunEnvBackend=PROD
      - DatabaseEndpoint=http://prometheus:9090/api/v1/query
      - NatsioEndpoints=nats://nats:4222
      - NatsioTopics=thesis.hcmut.data-upload.>
      - UserCredsPath=/etc/cred/pc.creds
      - KeyTLSPath=/etc/certs/client.key
      - CertTLSPath=/etc/certs/client.crt
      - RootCATLSPath=/etc/certs/rootCA.crt
    profiles:
      - test
  backend-prod:
    image: backend_release:latest
    restart: always
    privileged: true
    container_name: backendprod
    ports:
      - 5000:5000
    volumes:
      - ~/thesis_server_config/natsio_config:/etc/natsio_config
      - ~/thesis_logs/natsio:/var/log
      - ~/thesis_server_config/certs:/etc/certs
      - ~/thesis_server_config/cred:/etc/cred
    environment:
      - ContainerName=backend-prod
      - RunEnvBackend=PROD
      - DatabaseEndpoint=http://prometheus:9090/api/v1/query
      - NatsioEndpoints=nats://nats:4222
      - NatsioTopics=thesis.hcmut.data-upload.>
      - UserCredsPath=/etc/cred/pc.creds
      - KeyTLSPath=/etc/certs/client.key
      - CertTLSPath=/etc/certs/client.crt
      - RootCATLSPath=/etc/certs/rootCA.crt
    profiles:
      - prod
